In [1]:
%pip install torch torchvision torchaudio 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 4.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 4.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.9/679.9 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [torchvision] [torchvision]
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

In [3]:
print(f"Pytorch Version: {torch.__version__}")

Pytorch Version: 2.12.0


In [4]:
# 2. Check for Apple Silicon GPU (MPS) support
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    print("Success! Found Apple Silicon GPU (MPS).")
else:
    mps_device = torch.device("cpu")
    print("MPS not found. Falling back to CPU.")

Success! Found Apple Silicon GPU (MPS).


<!-- Random tensors -->
Why Random Tensors?
Randome tensors are imp bcoz the way neural networks learn is they start with tensors full of random. umbers. Then adjust those numbers to better represent the data


In [5]:
matrix_a = torch.randn(3,4)
print(matrix_a)

tensor([[-1.4383,  0.2568,  0.5357,  0.5951],
        [-0.1743,  0.7302,  0.3159, -1.2019],
        [-0.3574, -1.3931,  0.8006,  0.8170]])


In [6]:
matrix_b = torch.randn(4,2)
print(matrix_b)

tensor([[-0.6187, -1.0113],
        [ 2.0384, -1.2520],
        [-0.3906, -1.2282],
        [-0.7971,  0.0029]])


In [7]:
print("Matrix A Shape:", matrix_a.shape)
print("Matrix B Shape:", matrix_b.shape)

Matrix A Shape: torch.Size([3, 4])
Matrix B Shape: torch.Size([4, 2])


In [8]:
# 2. Perform Matrix Multiplication
# In PyTorch, '@' is the operator for matrix multiplication
result = matrix_a @ matrix_b

In [9]:
print("\nResulting Matrix Shape:",result.shape)


Resulting Matrix Shape: torch.Size([3, 2])


In [10]:
print("\nResulting Data:\n",result)


Resulting Data:
 tensor([[ 0.7298,  0.4769],
        [ 2.4309, -1.1294],
        [-3.5825,  1.1247]])


In [11]:
print("\nDevice being used:", result.device)


Device being used: cpu


In [12]:
result.ndim

2

In [14]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # Height x Width x Channels
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


Zeros and ones

In [15]:
#Create a tensor of all zero

zeros = torch.zeros(3,4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [16]:
ones = torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
ones.dtype

torch.float32

Creating range of tensors and tensor-like

In [18]:
# use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten = torch.arange(1,11)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [20]:
one_to_thousand = torch.arange(start=1,end=1000,step=10)
print(one_to_thousand)

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
        281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
        421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
        561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
        701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
        841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
        981, 991])


In [21]:
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors with PyTorch deep learning
1. Tensor is not right datatype
2.Tensor not right shape
3.Tensor not on the right device

In [27]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
print(float_32_tensor.dtype)
print(float_32_tensor)

torch.float32
tensor([3., 6., 9.])


In [28]:
#Convert float 32 to 16
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)
print(float_16_tensor)

torch.float16
tensor([3., 6., 9.], dtype=torch.float16)
