In [3]:
%pip install torch torchvision torchaudio 

  Using cached torchaudio-2.11.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (6.9 kB)
Using cached torchaudio-2.11.0-cp313-cp313-macosx_12_0_arm64.whl (679 kB)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch

In [5]:
print(f"Pytorch Version: {torch.__version__}")

Pytorch Version: 2.10.0


In [6]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:

# Check the number of dimensions of vector
vector.ndim

1

In [10]:
# Check shape of vector
vector.shape

torch.Size([2])

In [11]:
# 2. Check for Apple Silicon GPU (MPS) support
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    print("Success! Found Apple Silicon GPU (MPS).")
else:
    mps_device = torch.device("cpu")
    print("MPS not found. Falling back to CPU.")

Success! Found Apple Silicon GPU (MPS).


<!-- Random tensors -->
Why Random Tensors?
Randome tensors are imp bcoz the way neural networks learn is they start with tensors full of random. umbers. Then adjust those numbers to better represent the data


In [12]:
matrix_a = torch.randn(3,4)
print(matrix_a)

tensor([[ 0.3591, -0.0324, -0.8092, -0.2340],
        [ 1.4989,  0.5612,  0.0134, -1.4657],
        [-0.6162, -0.9531, -1.1474, -0.5665]])


In [13]:
matrix_b = torch.randn(4,2)
print(matrix_b)

tensor([[-0.2211, -0.1081],
        [-1.1251, -1.1862],
        [-1.7295,  0.0616],
        [-1.5689, -1.1084]])


In [14]:
print("Matrix A Shape:", matrix_a.shape)
print("Matrix B Shape:", matrix_b.shape)

Matrix A Shape: torch.Size([3, 4])
Matrix B Shape: torch.Size([4, 2])


In [15]:
# 2. Perform Matrix Multiplication
# In PyTorch, '@' is the operator for matrix multiplication
result = matrix_a @ matrix_b

In [16]:
print("\nResulting Matrix Shape:",result.shape)


Resulting Matrix Shape: torch.Size([3, 2])


In [17]:
print("\nResulting Data:\n",result)


Resulting Data:
 tensor([[1.7237, 0.2091],
        [1.3136, 0.7978],
        [4.0818, 1.7543]])


In [18]:
print("\nDevice being used:", result.device)


Device being used: cpu


In [19]:
result.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # Height x Width x Channels
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


Zeros and ones

In [21]:
#Create a tensor of all zero

zeros = torch.zeros(3,4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
ones = torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
ones.dtype

torch.float32

Creating range of tensors and tensor-like

In [24]:
# use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(1,11)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [26]:
one_to_thousand = torch.arange(start=1,end=1000,step=10)
print(one_to_thousand)

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271,
        281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391, 401, 411,
        421, 431, 441, 451, 461, 471, 481, 491, 501, 511, 521, 531, 541, 551,
        561, 571, 581, 591, 601, 611, 621, 631, 641, 651, 661, 671, 681, 691,
        701, 711, 721, 731, 741, 751, 761, 771, 781, 791, 801, 811, 821, 831,
        841, 851, 861, 871, 881, 891, 901, 911, 921, 931, 941, 951, 961, 971,
        981, 991])


In [27]:
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors with PyTorch deep learning
1. Tensor is not right datatype
2.Tensor not right shape
3.Tensor not on the right device

In [28]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
print(float_32_tensor.dtype)
print(float_32_tensor)

torch.float32
tensor([3., 6., 9.])


In [29]:
#Convert float 32 to 16
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)
print(float_16_tensor)

torch.float16
tensor([3., 6., 9.], dtype=torch.float16)


In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## tensor.dtype, tensor.shape, tensor.device, tensor.ndim, tensor.requires_grad

In [31]:
some_tensor = torch.randn(3,4)
print(some_tensor)  
print(f"Datatype before: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Shape of tensor:{some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[-0.1237, -0.9102,  0.4438,  0.1473],
        [ 2.2037, -0.2061, -1.2986,  0.6440],
        [ 1.2795, -0.0446, -0.9702, -0.9665]])
Datatype before: torch.float32
Shape of tensor:torch.Size([3, 4])
Shape of tensor:torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
 * Addition
 * Subtract
 * Multiplication
 * Division
 *MAtrix multiplication

In [32]:
#Create a tesnor and add something

tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [33]:
#Multiply
tensor1 = torch.tensor([1,2,3])
tensor1 * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
# try pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 556 μs, sys: 760 μs, total: 1.32 ms
Wall time: 770 μs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 137 μs, sys: 145 μs, total: 282 μs
Wall time: 184 μs


tensor(14)